'use client';
import {useEffect,useState} from 'react';
type Snapshot={state:null|{status:string;lane:string;lastAttemptAt:number;lastSuccessAt:number;nextAt:number;leaseUntil:number;resultJson:string};monitor:null|{pausedAt:string|null;active:number};graph:{total:number;complete:number;partial:number;pending:number;blocked:number};routes:{total:number;checked:number;related:number;insufficient:number}};
export function ResearchMaintenance({spaceId,trackId='',locale}:{spaceId:string;trackId?:string;locale:'zh'|'en'}) {
  const [data,setData]=useState<Snapshot|null>(null),[unavailable,setUnavailable]=useState(false),[now,setNow]=useState(()=>Date.now());
  const zh=locale==='zh';
  useEffect(()=>{const abort=new AbortController();const refresh=async()=>{if(document.hidden)return;try{const r=await fetch(`/api/research-maintenance?spaceId=${encodeURIComponent(spaceId)}&trackId=${encodeURIComponent(trackId)}`,{signal:abort.signal});if(!r.ok)throw Error();const next=await r.json() as Snapshot;if(!abort.signal.aborted){setData(next);setNow(Date.now());setUnavailable(false);}}catch{if(!abort.signal.aborted)setUnavailable(true);}};void refresh();const timer=setInterval(()=>void refresh(),60000);return()=>{abort.abort();clearInterval(timer);};},[spaceId,trackId]);
  const state=data?.state;
  const status=unavailable?(zh?'暂时无法读取更新状态':'Update status unavailable'):!data?(zh?'读取后台进展…':'Loading background progress…'):data.monitor?.pausedAt?(zh?'本空间已暂停自动更新':'Automatic updates paused'):!data.monitor?.active?(zh?'等待恢复活跃后的调度':'Waiting for an active-space schedule'):state?.status==='running'&&state.leaseUntil>now?(zh?'正在整理材料':'Organizing papers'):state?.status==='unconfigured'?(zh?'路线核对需要服务端模型配置':'Route review needs a server model connection'):['retryable','error'].includes(state?.status||'')?(zh?'本轮未完成，等待重试':'This pass is incomplete; retry pending'):(zh?'后台分批更新，无需保持页面打开':'Updates run in batches; this page can be closed');
  let recent:Record<string,unknown>={};try{recent=JSON.parse(state?.resultJson||'{}');}catch{/* no fabricated result */}
  return <aside className="pi-research-maintenance" aria-label={zh?'后台研究进展':'Background research progress'}><div><strong>{zh?'后台研究进展':'Background research progress'}</strong><span>{status}</span></div>
    {data&&<p>{trackId?(zh?`本路线：已核对 ${data.routes.checked||0}/${data.routes.total} 个论文归属，${data.routes.related||0} 个相关，${data.routes.insufficient||0} 个依据不足`:`This route: ${data.routes.checked||0}/${data.routes.total} assignments checked, ${data.routes.related||0} related, ${data.routes.insufficient||0} insufficient`):(zh?`引用：${data.graph.complete||0} 篇查询完成 · ${data.graph.partial||0} 篇部分覆盖 · ${data.graph.pending||0} 篇待查 · ${data.graph.blocked||0} 篇受阻`:`Citations: ${data.graph.complete||0} complete · ${data.graph.partial||0} partial · ${data.graph.pending||0} pending · ${data.graph.blocked||0} blocked`)}</p>}
    {state?.lastAttemptAt? <p>{zh?'最近处理':'Last attempt'}：{new Date(state.lastAttemptAt).toLocaleString(zh?'zh-CN':'en-US')}{state.nextAt?` · ${zh?'下次可调度':'Next eligible'} ${new Date(state.nextAt).toLocaleString(zh?'zh-CN':'en-US')}`:''}</p>:null}
    <details><summary>{zh?'查看更新范围与最近结果':'Update scope and latest result'}</summary><p>{zh?'新材料自动参与路线相关性核对，引用按批次补查；成功查询通常每周刷新。活跃空间沿用 7 天活动窗口，暂停设置仍生效。下次可调度时间不是完成期限。':'New papers enter route review; citations are checked in batches and successful lookups normally refresh weekly. The existing seven-day activity window and pause settings still apply. Eligibility time is not a completion deadline.'}</p>
      {!!recent.title&&<p>{zh?'最近材料':'Latest material'}：{String(recent.title)}{typeof recent.reviewed==='number'?` · ${zh?'已核对':'Reviewed'} ${recent.reviewed}`:''}{typeof recent.relations==='number'?` · ${zh?'已存关系':'Saved links'} ${recent.relations}`:''}</p>}
      <p>{zh?'自动相关性归类不代表质量推荐或正式证据；主干变更保留确认，学习完成状态由你决定。':'Automatic relevance does not establish quality or formal evidence. Backbone changes require confirmation; learning completion stays under your control.'}</p>
    </details></aside>;
}
